import { useState } from 'react'
import { ArrowLeft, ArrowRight, BookOpenCheck, Check, Circle, Plus, Target } from 'lucide-react'
import { useJournal } from '../hooks/useJournal'
import { calculateStats, currency, percent } from '../utils/trading'
import { EmptyState } from '../components/UiElements'

export default function Playbooks() {
  const [selected, setSelected] = useState(null)
  const { filteredTrades, playbooks = [], setPlaybooks, playbookChecklists: checked, setPlaybookChecklists, notify } = useJournal()
  const getPerformance = (book) => calculateStats(filteredTrades.filter((trade) => trade.strategy === book.name))
  const createPlaybook = () => {
    const name = `My playbook ${playbooks.length + 1}`
    const book = { id: `playbook-${Date.now()}`, name, description: 'A simple starting point for documenting a repeatable setup.', entry: ['Define the setup and market context', 'Confirm entry criteria before placing the trade'], exit: ['Set risk before entry', 'Record the exit reason after the trade'], short: 'New setup', color: 'purple', trades: 0, winRate: 0, profitFactor: 0 }
    setPlaybooks((current) => [book, ...current])
    setSelected(book)
    notify?.('Starter playbook created.')
  }
  if (selected) {
    const metrics = getPerformance(selected)
    return <div className="page-content"><button className="back-link" onClick={() => setSelected(null)}><ArrowLeft size={16} />All playbooks</button><section className="panel playbook-detail"><div className="playbook-detail-head"><div className="playbook-large-icon"><BookOpenCheck size={23} /></div><div><span className="eyebrow">STRATEGY PLAYBOOK</span><h2>{selected.name}</h2><p>{selected.description}</p></div><button className="button-secondary" onClick={() => window.alert('Playbook templates can be edited from this strategy card in a future release.')}><Plus size={15} />Edit playbook</button></div><div className="playbook-performance">{[['Win rate', metrics.trades ? percent(metrics.winRate) : '—'], ['Profit factor', metrics.trades && Number.isFinite(metrics.profitFactor) ? metrics.profitFactor.toFixed(2) : '—'], ['Trades logged', metrics.trades], ['Net P&L', metrics.trades ? currency(metrics.netPnl) : '—']].map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><div className="playbook-rules-grid"><article><h3><Target size={17} />Entry rules</h3>{selected.entry.map((rule, index) => <div className="playbook-rule" key={rule}><span>{String(index + 1).padStart(2, '0')}</span>{rule}</div>)}</article><article><h3><ArrowRight size={17} />Exit rules</h3>{selected.exit.map((rule, index) => <div className="playbook-rule" key={rule}><span>{String(index + 1).padStart(2, '0')}</span>{rule}</div>)}</article></div><article className="checklist-panel"><h3>Pre-trade checklist</h3>{['Setup matches my entry criteria', 'Risk is clearly defined', 'No high-impact news nearby', 'I am trading from a calm mindset'].map((item) => { const key = `${selected.name}:${item}`; return <button key={item} onClick={() => setPlaybookChecklists((current) => ({ ...current, [key]: !current[key] }))}><span className={`checkbox ${checked[key] ? 'checkbox-on' : ''}`}>{checked[key] && <Check size={12} />}</span>{item}</button> })}</article></section></div>
  }
  return <div className="page-content"><div className="page-intro-row"><div><span className="eyebrow">TRADE WITH INTENTION</span><h2>Your strategy library</h2><p>Turn your best setups into a repeatable process.</p></div><button className="button-primary" onClick={createPlaybook}><Plus size={16} />New playbook</button></div>{playbooks.length === 0 && <section className="panel page-empty-panel"><EmptyState icon={BookOpenCheck} title="Build your first playbook" description="Write down the setup rules you want to follow consistently." action={<button type="button" className="button-primary" onClick={createPlaybook}>Create a playbook</button>} /></section>}<div className="playbook-grid">{playbooks.map((book) => { const metrics = getPerformance(book); return <button className="panel playbook-card" key={book.id || book.name} onClick={() => setSelected(book)}><div className={`playbook-icon ${book.color}`}><BookOpenCheck size={20} /></div><div className="playbook-card-title"><div><h3>{book.name}</h3><p>{book.description}</p></div><ArrowRight size={17} /></div><div className="playbook-card-stats"><div><strong>{metrics.trades ? percent(metrics.winRate) : '—'}</strong><span>Win rate</span></div><div><strong>{metrics.trades && Number.isFinite(metrics.profitFactor) ? metrics.profitFactor.toFixed(2) : '—'}</strong><span>Profit factor</span></div><div><strong>{metrics.trades}</strong><span>Trades</span></div></div><div className="playbook-card-footer"><span><Circle size={7} fill="currentColor" /> Active playbook</span><span>Details <ArrowRight size={13} /></span></div></button> })}<button className="new-playbook-card" onClick={createPlaybook}><span><Plus size={19} /></span><strong>Create a playbook</strong><small>Document a setup that works for you</small></button></div></div>
}
